baseURL = 'https://audepe.cloud/'
languageCode = 'en-us'
title = "Audepe's Blog"
theme = 'hugo-coder'
enableEmoji = true

[params]
author = "Daniel Delgado"
description = "Daniel Delgado's website"
keywords = "blog,devops,personal"
info = ["DevOpsğŸ’¡ğŸ’»", "Systems MagicianğŸ”§ğŸ§™â€â™‚ï¸"]
colorScheme = "auto"
avatarURL = "images/avatar.jpg"

[menu]
   [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/" 
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
